FROM node:lts-alpine

ARG INSTALL_ZSH="true"
ARG USERNAME=vscode
ARG USER_UID=10000
ARG USER_GID=$USER_UID
ARG INSTALL_OH_MYS="true"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

ARG COMMON_SCRIPT_SOURCE="https://raw.githubusercontent.com/microsoft/vscode-dev-containers/master/script-library/common-alpine.sh"

RUN apk update \
    && apk add --no-cache wget coreutils ca-certificates \
    && wget -q -O /tmp/common-setup.sh ${COMMON_SCRIPT_SOURCE} \
    && /bin/ash /tmp/common-setup.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${INSTALL_OH_MYS}" \
    && rm /tmp/common-setup.sh

RUN echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER ${USER_UID}:${USER_GID}
WORKDIR /home/${USERNAME}